### ISSUE TITLE
Self-hosted Runner on MacOS asking for password

### ISSUE THREAD

**Issue by ibebbs** [maxim-lobanov/setup-xamarin#10]
Hi,

Thanks for this action, it's working perfectly when used within hosted runners on Github. However, Github's 10x minutes usage for MacOS builds is killing my allowance so I'm trying to set up a self-hosted runner.

I followed all the Github instruction and the runner starts and waits for Jobs correctly. Unfortunately, when it starts running my build job and encounters the `setup-xamarin` (v1.1) action, the self-hosted runner prompts for a password.

I believe this is due to commands the action is invoking which require 'sudo' priviledges. Looking this up, it appears that [sudo should run passwordless](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#administrative-privileges-of-github-hosted-runners) which makes me believe `sudo` is not being specified as part of the command.

Looking at the source code for the action, I can see that [options can be specified such that `sudo` is prefixed to the command](https://github.com/maxim-lobanov/setup-xamarin/blob/719c9a2aaec29cf198784cddb4d79c592859cfe8/src/utils.ts#L11) but I can't find any instructions on how to specify these options.

Could you point me in the direction of instructions or example build scripts that specify these options?

Thanks again,
  Ian

**Comment by ibebbs** [comment]
My apologies, it appears the step before setup-xamarin was causing the issue. Closing this.

**Comment by maxim-lobanov** [comment]
Hello @ibebbs!
After disabling previous step, this action started to look as expected?
I guess that this action could be affected too.

The action runs all commands with sudo but if your self-hosted machine has some password for sudo - it won't work and will hang on password prompt

**Comment by ibebbs** [comment]
Hi Maxim,

Thanks for getting back to me and sorry again for the misdirection about the issue.

The step before is checkout (v2) and is asking for - I believe - my Github password, not a password for sudo. This is odd as the machine has an SSH key for checkout and I've also tried using a Personal Access Token to no avail. All a bit frustrating to be honest.

Anyway, if I do encounter any issues with `setup-xamarin` I'll let you know.
