### ISSUE TITLE
What does `latest` mean?

### ISSUE THREAD

**Issue by knocte** [maxim-lobanov/setup-xamarin#4]
I see in the README that you can use `latest` as the version of Xamarin to choose, but what does this exactly mean? Latest in the stable channel? or could that mean beta/preview channels?

**Comment by maxim-lobanov** [comment]
It means `latest` in stable channel.
This action can't download versions in runtime (during the build). It just switches between pre-installed versions. On Hosted images, only stable versions are pre-installed.

**Comment by knocte** [comment]
Ok cool (this is what I wanted, I don't want anything newer than stable channels). Maybe it's good to mention this in the README.
