### ISSUE TITLE
Latest version is a lower version than previous?

### ISSUE THREAD

**Issue by ianschmitz** [maxim-lobanov/setup-xamarin#6]
It appears the released versions for this action are `v1.0 -> v1.1 -> v1`, where `v1` is the latest. Is that intentional? Should `v1` also be tagged something like `v1.2`?

**Comment by maxim-lobanov** [comment]
Hello!
Yes, it is expected.
`v1` tag points to the latest `v1.x`.
This action is following semantic versioning recommended by GitHub in https://github.com/actions/toolkit/blob/main/docs/action-versioning.md

**Comment by ianschmitz** [comment]
Right understood. I should have been more specific. Right now there doesn't appear to be a v1.2 release that we can target, only v1

**Comment by maxim-lobanov** [comment]
Oh, I got your point. Too little coffee today morning 👍 
It should be `v1.2` tag and `v1` that points to it.

Let me fix it.

**Comment by maxim-lobanov** [comment]
Fixed, thank you for pointing it.
